services:
  - type: web
    name: daily-chex
    plan: free
    runtime: node
    buildCommand: npm run render-build
    startCommand: npm run render-start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        value: production
